### ISSUE TITLE
leader follower formation

### ISSUE THREAD

**Issue by amehr90** [lis-epfl/swarmlab#5]
i am trying to implement leader follower on 2 quadcopters using pixhawk can you help me out in my project?

**Comment by EnricaSo** [comment]
Hello @amehr90,

If you want to implement SITL simulation with the drone firmware running in the loop, you may be interested in reading [this](https://docs.px4.io/master/en/simulation/gazebo.html).

Swarmlab is not intended to run SITL simulation. However, it may be helpful to validate your swam algorithm in Swarmlab before proceeding to the implementation on the drones. To do so, you could implement your own leader-follower controller in a new file inside the [@Swarm](https://github.com/lis-epfl/swarmlab/tree/master/%40Swarm) folder. This way your controller will be a method of the Swarm class and you can access all the Swarm variables.
